### ISSUE TITLE
The first link leads to a 404 error

### ISSUE THREAD

**Issue by rcshubhadeep** [shahrukhx01/adversarial-ml-101#8]
The first link in the readme `Training and anlysisi of the parametric and non-parametric ML models on MNIST dataset` leads to a 404 page as it is pointing to https://github.com/shahrukhx01/ml-cybersecurity/1_mnist_machine_learning_deep_learning.ipynb whereas the right link would be - https://github.com/shahrukhx01/adversarial-ml-101/blob/main/1_mnist_machine_learning_deep_learning.ipynb

**Comment by shahrukhx01** [comment]
@rcshubhadeep thanks for pointing this out, it's fixed now.
